.\" Man page describing chbspasswd
.\"
.\" Copyright (C) 2013-2014, Charles H. Leggett
.\"
.\" %%%LICENSE_START(GPLv3+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 3 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.\"
.\" Process this file with
.\" groff -man -Tascii chbspasswd.1
.\"
.TH CHBSPASSWD 1 "2013-12-10" chbspasswd "User Manual"
.SH NAME
chbspasswd \- generate a password which is easy to remember and hard to guess
.SH SYNOPSIS
.B chbspasswd [Options] [ -o
.I output-file
.B ]
.SH DESCRIPTION
.B chbspasswd
is a password generator inspired by XKCD 936: Password Strength and xkpasswd.net. It can generate a customized password that is easy to remember and hard to guess.
.SH OPTIONS
.IP -c
Number (or count) of passwords to generate.
.IP "-o output-file"
Filename to write passwords to instead of to standard out.
.SH FILES
.I ~/.chbspasswdrc
.RS
Per user configuration file. See
.BR chbspasswd (5)
for further details.
.SH AUTHOR
Charles H. Leggett <charles@solarturtle.net>
